version: 2
search:
  ignore:
    - fakedata/*.html

mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements_dev.txt
    - method: setuptools
      path: .
