version: 2
search:
  ignore:
    - fakedata/*.html

mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --group docs --frozen
    - uv run mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
